- name: play 
  hosts: local
  connection: local
  vars: 
    COURSE: "DevOps with AWS"
    DURATION: "140HRS"
    TRAINER: "Krishna"
    
  tasks:
   - name: print variable
     ansible.builtin.debug:
      msg: "Coruse is : {{ COURSE }}, {{ TRAINER }}"