- name: Print username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Please enter your user name
    private: false

  - name: password
    prompt: Please enter your password
    private: true
    