- name: demo on conditions
  hosts: local
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 7
  tasks:
  - name: Is ansible nire than 5 session
    ansible.builtin.debug:
      msg: "yes, more than 5 session"
    when: NUMBER_OF_SESSIONS > 5
    