- name: condition with inventory
  hosts: db
  tasks:
    - name: checking condition on when
      ansible.builtin.debug:
        msg: "This runs only on DB group"
      when: "'web' not in group_names"