- name: condition with inventory
  hosts: all
  tasks:
    - name: checking condition on when
      ansible.builtin.debug:
        msg: "Configuring WEB server"
      when: "'web' in group_names"

    - name: checking condition on when
      ansible.builtin.debug:
        msg: "Configuring DB server"
      when: "'db' in group_names"