- name: loops concept
  hosts: localhost
  connection: local
  gather_facts: no

  tasks: 
    - name: print items
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - apple 
        - banana
        - mango