- name: loops concept
  hosts: localhost
  connection: local
  gather_facts: no

  tasks: 
    - name: installing packages
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      
      loop:
        - git
        - nginx