- name: test 36 loop with variable
  hosts: localhost
  connection: localhost
  vars:
    loop: 
      - git
      - nginx
      - curl
  
  tasks: 
    - name: installing package
      ansible.builtit.debug:
        msg: "installing {{ item }}"
        
