- name: test 32 on loops
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: installing the package
      ansible.builtin.debug:
        msg: " installing {{ item }}"
            
      loop:
        - git
        - nginx
        - curl