- name: test 34 on loops + when
  hosts: localhost
  become: yes

  tasks:
    - name: installing the package
      ansible.builtin.debug:
        msg: "installing {{ item }}"
          
      loop:
        - git
        - nginx
        - curl
      when: "item  == nginx"