- name: test facts 2
  hosts: localhost
  connection: local
  
  tasks:
    - name: Print ansible hostname and ansible distribution
      ansible.builtin.debug:
        msg: "This is redhat Linux"
      when: ansible_distribution == "Redhat"
