- name: Facts test 1
  hosts: localhost
  connection: local
  vars:
    var: ansible_facts
  tasks:
    - name: print os name
      ansible.builtin.debug:
        msg: "{{ ansible_facts.ansible_distribution }}"
        

