- name: demo on ingore erros
  hosts: localhost
  connection: local
  tasks:
    - name: Attempt to list non-existent directory
      ansible.builtin.command: ls testdir
      register: result1
      ignore_errors: yes

    - name: Confirm execution continues
      ansible.builtin.debug:
        msg: "Execution continued after failure"
