- name: demo on Idempotency
  hosts: localhost
  connection: local
  become: false
  
  tasks:
    # - name: create file using command (bad way)
    #   ansible.builtin.command: touch /tmp/idem_test.txt
    
    # - name: create file using file module (good way)
    #   ansible.builtin.file:
    #     path: /tmp/idem_test.txt
    #     state: touch # touch should not be used due to the it always create IF NOT exists OR update timestamp IF exists

    # - name: create file using file module (good way)
    #   ansible.builtin.file:
    #     path: /tmp/idem_file.txt
    #     state: file
    #     modification_time: preserve   # don't update mtime if file exists
    #     access_time: preserve         # don't update atime if file exists

   
    # - name: create empty file idempotently
    #   ansible.builtin.copy:
    #     content: ""          # empty file
    #     dest: /tmp/idem_file.txt
    #     force: false         # key: skip if file already exists

    - name: check if the file existent
      ansible.builtin.stat:
        path: /tmp/idem_file2.txt
      register: file_check

    - name: create a file only if missing
      ansible.builtin.commad: touch /tmp/idem_file2
      when: not file_check.stat.exists
