192.78.98.48
[frontend]
192.78.98.45
192.78.98.46
192.78.98.47

[backend]
192.78.98.45
192.78.98.46
192.78.98.47

[roboshop:children]
frontend
backend

[web]
server1 ansible_connection=local
server2 ansible_host=127.0.0.1

[local]
localhost

[local:vars]
COURSE= Ansible from inventory
NAME= "Ansible from inventory"